markdown: kramdown
permalink: /posts/:title.html

kramdown:
  input: GFM

title: 'Ушпешный блог'
description: 'О программировании, технологиях и жизни'
url: 'http://vasily.polovnyov.ru'
popular_posts: []
popular_post_urls:
  - "/posts/double-mock-stub.html"
  - "/posts/from-stylus-to-postcss.html"
  - "/posts/test-smells-ru.html"
  - "/posts/git-commit-messages.html"
  - "/posts/tests-junior.html"
  - "/posts/describe-vs-context.html"
  - "/posts/three-code-review-rules.html"
  - "/posts/css-inbox.html"
  - "/posts/stop-comments-deodorants.html"
  - "/posts/teenage-testing.html"
