markdown: redcarpet
permalink: /posts/:title.html

redcarpet:
  extensions: [strikethrough]

title: 'Записки успешного брограммиста'
description: 'О программировании, технологиях и жизни'
url: 'http://vasily.polovnyov.ru'
